runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images  

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest  